"""create id post user table+black

Revision ID: 30c0abe94c22
Revises: 30c0abe94c22
Create Date: 2022-09-21 17:46:49.814368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da268611d782"
down_revision = ""
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("post", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post")
    # ### end Alembic commands ###
