version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    environment:
      CONFIG: ProductionConfig
      SQLALCHEMY_DATABASE_URI: "postgresql://user:pass@pg/post"
    ports:
      - "8000:80"
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres
    environment:
      POSTGRES_DB: post
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
#    ports:
#      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: